variable "environment" {
  description = "Name of the environment; will be prefixed to all resources"
  type        = string
}

variable "project" {
  description = "Name of the project."
  type        = string
}

variable "vpc_id" {
  description = "EFS is created in this VPC"
  type        = string
}

variable "subnet_ids" {
  description = "The created EFS will be available in these subnet ids"
  type        = list(string)
}

variable "encrypted" {
  description = "Encrypt file system."
  type        = bool
  default     = true
}

variable "mount_location" {
  description = "Used to create a cloud init config part for amazon linux instances."
  type        = string
  default     = "/efs"
}

variable "performance_mode" {
  description = "maxIO"
  type        = string
  default     = "generalPurpose"
}

variable "creation_token" {
  description = "A unique name (a maximum of 64 characters are allowed) used as reference when creating the Elastic File System to ensure idempotent file system creation. By default generated by Terraform. "
  type        = string
  default     = ""
}

variable "transition_to_ia" {
  description = "Indicates how long it takes to transition files to the IA storage class. Valid values: AFTER_7_DAYS, AFTER_14_DAYS, AFTER_30_DAYS, AFTER_60_DAYS, or AFTER_90_DAYS."
  type        = string
  default     = null
}

variable "tags" {
  description = "A map of tags to add to the resources"
  type        = map(string)
  default     = {}
}

